import os
import requests
from enum import Enum
from typing import Optional, Type, Union

from pydantic import Field

from autobotAI_integrations import (
    BaseSchema,
    BaseService,
    ConnectionInterfaces,
    MCPCreds,
)
from autobotAI_integrations.models import IntegrationCategory
from autobotAI_integrations.utils.logging_config import logger


class ZohoMcpAuthTypes(str, Enum):
    SERVER_URL = "server_url"


class ZohoMcpIntegration(BaseSchema):
    name: str = "Zoho MCP"
    category: Optional[str] = IntegrationCategory.NOTIFICATIONS_AND_COMMUNICATIONS.value
    description: Optional[str] = (
        "Zoho MCP Server integration dynamically connects to custom or hosted Zoho Model Context Protocol servers to execute tools for Cliq messaging, CRM, Desk, and organizational operations in Optimus agents."
    )
    auth_type: Optional[str] = ZohoMcpAuthTypes.SERVER_URL.value
    server_url: str = Field(
        ...,
        description="The streamable HTTP endpoint of the Zoho MCP server (e.g. https://autobot-zoho-server-...zohomcp.in/mcp/...)",
    )
    api_key: Optional[str] = Field(
        default=None,
        exclude=True,
        description="Optional API Key, Webhook Token, or OAuth Token for authenticating with the MCP server.",
    )

    @property
    def base_url(self) -> str:
        return self.server_url.strip().rstrip("/")

    @property
    def mcp_base_url(self) -> str:
        return self.server_url.strip().rstrip("/")


class ZohoMcpService(BaseService):
    def __init__(self, ctx: dict, integration: Union[ZohoMcpIntegration, dict]):
        if not isinstance(integration, ZohoMcpIntegration):
            integration = ZohoMcpIntegration(**integration)
        super().__init__(ctx, integration)

    def _test_integration(self) -> dict:
        url = self.integration.server_url.strip()
        headers = {"Content-Type": "application/json"}
        token = (self.integration.api_key or "").strip()

        if token:
            headers["Authorization"] = f"Zoho-oauthtoken {token}"
            headers["apikey"] = token
            headers["zapikey"] = token

        try:
            # 1. Try MCP tools/list JSON-RPC request
            rpc_payload = {
                "jsonrpc": "2.0",
                "id": 1,
                "method": "tools/list",
                "params": {},
            }
            # Test direct URL and ?apikey= query variation if token is provided
            test_url = f"{url}?apikey={token}" if token and "?" not in url else url
            resp = requests.post(test_url, json=rpc_payload, headers=headers, timeout=10)

            if resp.status_code in [200, 204]:
                return {"success": True}

            # Zoho MCP endpoints return 400 with INVALID_INPUT JSON when alive
            if resp.status_code == 400:
                try:
                    data = resp.json()
                    if isinstance(data, dict) and ("status" in data or "error" in data or "data" in data):
                        return {"success": True}
                except Exception:
                    pass

            # 2. Try HTTP GET / ping on the endpoint
            get_resp = requests.get(test_url, headers=headers, timeout=10)
            if get_resp.status_code in [200, 204, 400, 401, 403, 405]:
                # Server responded and is reachable
                return {"success": True}

            return {
                "success": False,
                "error": f"MCP Server at {url} returned status code {resp.status_code}: {resp.text}",
            }
        except requests.exceptions.RequestException as e:
            logger.error(f"Zoho MCP connection test failed: {e}")
            return {"success": False, "error": f"Could not reach MCP server at {url}: {str(e)}"}

    @staticmethod
    def get_forms():
        return {
            "label": "Zoho MCP",
            "type": "form",
            "children": [
                {
                    "label": "MCP Server Configuration",
                    "type": "form",
                    "formId": ZohoMcpAuthTypes.SERVER_URL.value,
                    "children": [
                        {
                            "name": "server_url",
                            "type": "text/url",
                            "label": "Zoho MCP Server URL",
                            "placeholder": "https://autobot-zoho-server-...zohomcp.in/mcp/...",
                            "description": "The Streamable HTTP / SSE endpoint generated by your Zoho MCP Server (contains server token and pre-authorized connection).",
                            "required": True,
                            "help_url": "https://mcp.zoho.in",
                            "help_url_text": "Zoho MCP Portal ->",
                        },
                    ],
                }
            ],
        }

    @staticmethod
    def get_schema(ctx=None) -> Type[BaseSchema]:
        return ZohoMcpIntegration

    @staticmethod
    def supported_connection_interfaces():
        return [
            ConnectionInterfaces.MCP_SERVER,
        ]

    def generate_mcp_creds(self) -> MCPCreds:
        headers = {"Content-Type": "application/json"}
        token = (self.integration.api_key or "").strip()
        if token:
            headers["Authorization"] = f"Zoho-oauthtoken {token}"
            headers["apikey"] = token
            headers["zapikey"] = token

        mcp_url = self.integration.mcp_base_url
        envs = {
            "ZOHO_MCP_URL": mcp_url,
            "ZOHO_MCP_TOKEN": token,
        }
        return MCPCreds(
            url=mcp_url,
            headers=headers,
            envs=envs,
        )

