name: Run Pytest

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Steampipe
      run: |
        mkdir -p ~/.local/bin
        curl -L https://github.com/turbot/steampipe/releases/latest/download/steampipe_linux_amd64.tar.gz -o steampipe.tar.gz
        tar -xzf steampipe.tar.gz
        mv steampipe ~/.local/bin/
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        steampipe plugin install steampipe

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest python-dotenv
        pip install -e .
        
    - name: Run specific tests
      run: |
        # Run only specific test files - modify this list as needed
        pytest --disable-warnings tests/test_handlers -v
