name: Run Pytest

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Steampipe
      run: |
        /bin/sh -c "$(curl -fsSL https://steampipe.io/install/steampipe.sh)"
        steampipe plugin install steampipe
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest python-dotenv
        pip install -e .
        
    - name: Run specific tests
      run: |
        # Run only specific test files - modify this list as needed
        pytest --disable-warnings tests/test_handlers -v
